version: '3'


tasks:
  build-dev:
    desc: Build frontend in dev mode
    cmds:
      - nix-shell --run "ng build --configuration development"
  serve-dev:
    desc: Serve frontend in dev mode
    cmds:
      - nix-shell --run "ng serve --configuration development"
