version: '3'


tasks:
  build-dev:
    desc: Build frontend in dev mode
    cmds:
      - nix-shell --run "ng build --configuration development"
  build-prod:
    desc: Build frontend in prod mode
    cmds:
      - nix-shell --run "ng build --configuration production"
  serve-dev:
    desc: Serve frontend in dev mode
    cmds:
      - nix-shell --run "ng serve --configuration development"
  serve-prod:
    desc: Serve frontend in prod mode
    cmds:
      - nix-shell --run "ng serve --configuration production"
  docker-build:
    deps: [build-prod]
    cmds:
      - docker build -t hnotes.frontend .
  k8s-deploy:
    deps: [docker-build]
    cmds:
      - "minikube-linux-amd64 kubectl -- delete deployment nginx-deployment --ignore-not-found"
      - "minikube-linux-amd64 image rm hnotes.frontend"
      - "minikube-linux-amd64 image load hnotes.frontend"
      - "minikube-linux-amd64 kubectl -- replace --force -f ../k8s/nginx.deployment.yaml"
      
