services:
  frontend:
    build:
      context: dockerfiles/frontend
    ports:
      - 80:80
    environment:
      NOTES_SERVICE_SERVICE_HOST: "notes"
      NOTES_SERVICE_SERVICE_PORT: 8080
      USERS_SERVICE_SERVICE_HOST: "users"
      USERS_SERVICE_SERVICE_PORT: 8090
  users:
    build:
      context: dockerfiles/users
    ports:
      - 8090:8090
  verification:
    build:
      context: dockerfiles/verification
    ports:
      - 5000:5000
  notes-db:
    build:
      context: dockerfiles/notes-db
    ports:
      - 3306:3306
  notes:
    build:
      context: dockerfiles/notes
    ports:
      - 8080:8080
    environment:
      NOTES_DB_SERVICE_SERVICE_HOST: "notes-db"
      NOTES_DB_SERVICE_SERVICE_PORT: 3306
      VERIFICATION_SERVICE_SERVICE_HOST: "verification"
      VERIFICATION_SERVICE_SERVICE_PORT: 5000
  elastic:
    image: elasticsearch:8.16.6
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
  artemis:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - 61616:61616
      - 8161:8161

