services:
  frontend:
    image: hnotes.frontend
    ports:
      - 80:80
    environment:
      NOTES_SERVICE_SERVICE_HOST: "notes"
      NOTES_SERVICE_SERVICE_PORT: 8080
      USERS_SERVICE_SERVICE_HOST: "users"
      USERS_SERVICE_SERVICE_PORT: 8090
  users:
    image: hnotes.users
    ports:
      - 8090:8090
  verification:
    image: hnotes.verification
    ports:
      - 5000:5000
    environment:
      HNOTES_ARTEMIS_HOST: "artemis"
      HNOTES_ARTEMIS_PORT: 61616
  notes-db:
    image: hnotes.notes-db
    ports:
      - 3306:3306
  notes:
    image: hnotes.notes
    ports:
      - 8080:8080
    environment:
      NOTES_DB_SERVICE_SERVICE_HOST: "notes-db"
      NOTES_DB_SERVICE_SERVICE_PORT: 3306
      VERIFICATION_SERVICE_SERVICE_HOST: "verification"
      VERIFICATION_SERVICE_SERVICE_PORT: 5000
      ARTEMIS_HOST: "artemis"
      ARTEMIS_PORT: 61616
      ELASTIC_SERVICE_HOST: "elasticsearch"
      ELASTIC_SERVICE_PORT: 9200
  status:
    image: hnotes.status
    ports:
      - 8100:8100
    environment:
      ARTEMIS_HOST: "artemis"
      ARTEMIS_PORT: 61616
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms128m -Xmx2g
      - cluster.routing.allocation.disk.watermark.low=200mb
      - cluster.routing.allocation.disk.watermark.high=200mb
      - cluster.routing.allocation.disk.watermark.flood_stage=200mb
  artemis:
    image: hnotes.artemis
    ports:
      - 61616:61616
      - 8161:8161

