services:
  frontend:
    build:
      context: dockerfiles/frontend
    ports:
      - 80:80
    environment:
      NOTES_SERVICE_SERVICE_HOST: "notes"
      NOTES_SERVICE_SERVICE_PORT: 8080
      USERS_SERVICE_SERVICE_HOST: "users"
      USERS_SERVICE_SERVICE_PORT: 8090
  users:
    build:
      context: dockerfiles/users
    ports:
      - 8090:8090
  verification:
    build:
      context: dockerfiles/verification
    ports:
      - 5000:5000
  notes-db:
    build:
      context: dockerfiles/notes-db
    ports:
      - 3306:3306
  notes:
    build:
      context: ../backend/notes_service
    ports:
      - 8080:8080
    environment:
      NOTES_DB_SERVICE_SERVICE_HOST: "notes-db"
      NOTES_DB_SERVICE_SERVICE_PORT: 3306
      VERIFICATION_SERVICE_SERVICE_HOST: "verification"
      VERIFICATION_SERVICE_SERVICE_PORT: 5000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms128m -Xmx2g
      - cluster.routing.allocation.disk.watermark.low=200mb
      - cluster.routing.allocation.disk.watermark.high=200mb
      - cluster.routing.allocation.disk.watermark.flood_stage=200mb
  artemis:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - 61616:61616
      - 8161:8161

