apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: notes-db
  template:
    metadata:
      labels:
        db: notes-db
    spec:
      containers:
      - name: notes-db
        image: hnotes.notesdb:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: notes-db-service
  labels:
    run: notes-db-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    db: notes-db

