apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: hnotes.users:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    run: users-service
spec:
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    app: users

