apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
      - name: verification
        image: hnotes.verification:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: verification-service
  labels:
    run: verification-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: verification

