version: '3'

tasks:
  build:
    cmds:
      - nix-shell --run "mvn package"
  run:
    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: houen
      DB_PASSWORD: houen
      DB_NAME: notesdatabase
      VERIFICATION_SERVICE_HOST: localhost
      VERIFICATION_SERVICE_PORT: 5000
    cmds:
      - nix-shell --run "./mvnw spring-boot:run"
  docker-build:
    deps: [build]
    cmds:
      - docker build -t hnotes.notes -f ./Dockerfile .
  docker-build-db:
    cmds:
      - docker build -t hnotes.notes-db -f ./Db.Dockerfile .
