#!/bin/sh

# TODO: fix db_username
export DB_NAME=admin
export DB_USERNAME=houen
export DB_PASSWORD=houen
export DB_HOST=${MONGODB_SERVICE_SERVICE_HOST}
export DB_PORT=${MONGODB_SERVICE_SERVICE_PORT}

export VERIFICATION_SERVICE_HOST=${VERIFICATION_SERVICE_SERVICE_HOST}
export VERIFICATION_SERVICE_PORT=${VERIFICATION_SERVICE_SERVICE_PORT}

java -Xmx256m -jar /app/hnotes-notes.jar
